import { Student } from "@/app/student-page/studentcolumns";
import { RootState } from "@/redux/store/store";
import { StudentData } from "@/types/student";
import { useCreate } from "@refinedev/core";
import { useRouter } from "next/navigation";
import { FieldValues, useForm } from "react-hook-form";
import { useSelector } from "react-redux";
import { toast } from "sonner";

export const useAddStudentForm = () => {

  const router = useRouter();

  const institute_id = useSelector((state: RootState) => state.auth.institute_uuid);
  const institute_name = useSelector((state: RootState) => state.auth.institute_name);

  
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<Partial<StudentData>>({
    defaultValues: {
      student_name: "",
      department: "",
      email: "",
      phone_no: "",
      address: "",
      roll_no: 0,
      year_of_admission: "",
      password: "",
      confirm_password: "",
      date_of_birth: "",
      gender: "",
    },
  });
  const { mutate, isLoading } = useCreate();

  const onSubmit = (data: FieldValues) => {

    const studentData: Student = {
      student_id: "", // Will be generated by backend
      student_uuid: "",
      student_name: data.student_name,
      department: data.department,
      email: data.email,
      phone_no: data.phone_no,
      address: data.address,
      roll_no: Number(data.roll_no),
      year_of_admission: data.year_of_admission,
      password: data.password,
      confirm_password: data.confirm_password,
      is_archived: false,
      date_of_birth: data.date_of_birth,
      gender: data.gender,
      institute_id:institute_id ?? "",  // TODO: Change intitute Id to intitute_uuid
      institute_name: institute_name?? "",
    };

    mutate(
      { resource: "student/create", values: studentData },
      {
        onSuccess: () => {
          toast.success("Student added successfully!");
          router.push("/student-page");
        },
        onError: (error: any) => {
          toast.error("Error adding student: " + error.message);
        },
      }
    );
  };

  return { register, handleSubmit, errors, onSubmit, isLoading };
};
