import StudentDirectory from "@/app/student-page/page";

const images = {
  AddBook: require("./addbook.png"),
  AddTab: require("./AddTab.png"),
  ArrowLeft: require("./arrow-left.png"),
  ArrowRight: require("./arrow-right.png"),
  AvailableBooks: require("./Available_Books.png"),
  BookBorrowed: require("./BookBorrowed.png"),
  BookReturned: require("./BookReturned.png"),
  BooksLogo: require("./BooksLogo.png"),
  BorrowedBooks: require("./Borrowed_Books.png"),
  Calendar: require("./calender.png"),
  ChevronDown: require("./chevron-down.png"),
  Cloud: require("./cloud.png"),
  Dash: require("./Dash.png"),
  DashLogo: require("./DashLogo.png"),
  DeleteButton: require("./deleteBtn.png"),
  Dropdown: require("./dropdown.png"),
  Dropper: require("./Dropper.png"),
  Edit: require("./edit.png"),
  EditButton: require("./EditBtn.png"),
  EditIcon: require("./editicon.png"),
  FeesPenalties: require("./FeesPenaltiesLogo.png"),
  Filter: require("./filter.png"),
  HomeIcon: require("./HomeIcon.png"),
  Import: require("./import.png"),
  ImportDrop: require('./importdrop.png'),
  IssuedBooks: require("./IssuedBooks.png"),
  IssuedBooksLogo: require("./IssuedBooksLogo.png"),
  Logo: require("./Logo.png"),
  Logout: require("./logout.png"),
  LostBooks: require("./Lost_Books.png"),
  NoBookIllustration: require("./noBookillustration.png"),
  PenIcon: require("./penicon.png"),
  Search: require("./search.png"),
  StudentDirectory: require("./StudentDirectory.png"),
  Telephone: require("./telephone.png"),
  TIA: require("./Tia.png"),
  TotalBooks: require("./Total_Books.png"),
  Thrash: require("./trash.png"),
  Vector: require("./Vector.png"),
  VighnotechLogo: require("./VighnotechLogo.png"),
  VisitLogo: require("./VisitLogo.png"),
  Reports: require("./Reports.png"),
  BookShelf: require("./bookshelf.png"),
  TotalIssuedBooks: require("./TotalIssuedBooks.png"),
  Overdues: require("./Overdues.png"),
  TotalMembers:require("./TotalMembers.png"),
  Cancel:require("./cancel-01-stroke-rounded.svg"),
  config:require("./config.png"),
  TodayIssue:require("./TodayIssue.png"),
  TodayReturn:require("./TodayReturn.png")
};

export default images;
