// app/layout.tsx
import React from "react";
import { Metadata } from "next";
import { RefineContext } from "./_refine_context";
import Sidebar from "../app/Sidebar/sidebar";
import Navbar from "./Navbar/navbar";
import Header from "./Header/header";
import Tabbing from "./Tab/Tab";
import DonutChart from "./DonutChart/donutchart";
import BookCards from "./BookCards/bookcards";
import ActivityFeed from "./ActivityFeed/activityfeed";
import OrderedBooks from "./OrderedBooks/orderedbooks";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-screen m-0 p-0">
          <Sidebar />
          <div className="flex-1 flex flex-col overflow-scroll">
            <Navbar />
            <Header />
            <Tabbing />
            <div className="flex mt-10 gap-16">
              <DonutChart />
              <BookCards />
            </div>
            <div className="flex gap-2">
              <ActivityFeed />
              <OrderedBooks />
            </div>
            <div className="flex-1 p-16 overflow-y-auto">
              <RefineContext>{children}</RefineContext>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
