"use client";

import React from "react";
import Header from "../Header/header";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { useForm, FieldValues } from "react-hook-form";
import { useCreate } from "@refinedev/core";
import { useRouter } from "next/navigation";
import { Student } from "../student-page/studentcolumns";
import { toast } from "sonner";
import { useSelector } from "react-redux";
import { RootState } from "@/redux/store/store";

const AddStudent: React.FC = () => {
  const router = useRouter();
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<Student>({
    defaultValues: {
      student_name: "",
      department: "",
      email: "",
      phone_no: "",
      address: "",
      roll_no: "",
      year_of_admission: "",
      password: "",
      confirm_password: "",
      dob: "",
      gender: "",
    },
  });

  const { mutate } = useCreate();
  // Retrieve institute credentials from Redux auth state
  const auth = useSelector((state: RootState) => state.auth);

  // onSubmit function that receives the form data
  const onSubmit = (data: FieldValues) => {
    const hardcodedInstituteId = "828f0d33-258f-4a92-a235-9c1b30d8882b"; // Fallback if needed
    const hardcodedInstituteName = "Thakur Institute of Aviation"; // Fallback if needed

    // Create a studentData object with all required properties.
    // Note: Password and confirm_password will be submitted but not shown in the table.
    const studentData: Student = {
      student_id: "", // Will be generated by backend
      student_name: data.student_name,
      department: data.department,
      email: data.email,
      phone_no: data.phone_no,
      address: data.address,
      roll_no: data.roll_no,
      year_of_admission: data.year_of_admission,
      password: data.password,
      confirm_password: data.confirm_password,
      institute_id: auth.institute_uuid || hardcodedInstituteId, // using institute_uuid from Redux mapped to institute_id
      institute_name: auth.institute_name || hardcodedInstituteName, // institute name from Redux
      is_archived: false,
      dob: data.dob || "", // You may add a date picker if needed
      gender: data.gender || "",
    };

    mutate(
      { resource: "create", values: studentData },
      {
        onSuccess: () => {
          toast.success("Student added successfully!", { position: "top-center" });
          router.push("/student-page");
        },
        onError: (error: any) =>
          toast.error("Error adding student: " + error.message, { position: "top-center" }),
      }
    );
  };

  return (
    <>
      <Header />
      <section className="p-10">
        <div className="container mx-auto">
          <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
            <h2 className="text-2xl font-bold mb-4">Add Student</h2>
            <div className="grid grid-cols-2 gap-4">
              {/* Student Name */}
              <div>
                <Label>Full Name</Label>
                <Input
                  type="text"
                  {...register("student_name", { required: "Full Name is required" })}
                  placeholder="Enter Full Name"
                />
                {errors.student_name && (
                  <p className="text-red-500 text-sm">
                    {typeof errors.student_name.message === "string"
                      ? errors.student_name.message
                      : "An error occurred"}
                  </p>
                )}
              </div>
              {/* Department */}
              <div>
                <Label>Department</Label>
                <Input
                  type="text"
                  {...register("department", { required: "Department is required" })}
                  placeholder="Enter Department"
                />
                {errors.department && (
                  <p className="text-red-500 text-sm">
                    {typeof errors.department.message === "string"
                      ? errors.department.message
                      : "An error occurred"}
                  </p>
                )}
              </div>
              {/* Email */}
              <div>
                <Label>Email</Label>
                <Input
                  type="email"
                  {...register("email", { required: "Email is required" })}
                  placeholder="Enter Email"
                />
                {errors.email && (
                  <p className="text-red-500 text-sm">
                    {typeof errors.email.message === "string"
                      ? errors.email.message
                      : "An error occurred"}
                  </p>
                )}
              </div>
              {/* Phone Number */}
              <div>
                <Label>Phone Number</Label>
                <Input
                  type="text"
                  {...register("phone_no", { required: "Phone Number is required" })}
                  placeholder="Enter Phone Number"
                />
                {errors.phone_no && (
                  <p className="text-red-500 text-sm">
                    {typeof errors.phone_no.message === "string"
                      ? errors.phone_no.message
                      : "An error occurred"}
                  </p>
                )}
              </div>
              {/* Address */}
              <div>
                <Label>Address</Label>
                <Input
                  type="text"
                  {...register("address", { required: "Address is required" })}
                  placeholder="Enter Address"
                />
                {errors.address && (
                  <p className="text-red-500 text-sm">
                    {typeof errors.address.message === "string"
                      ? errors.address.message
                      : "An error occurred"}
                  </p>
                )}
              </div>
              {/* Roll No. */}
              <div>
                <Label>Roll No.</Label>
                <Input
                  type="text"
                  {...register("roll_no", { required: "Roll No. is required" })}
                  placeholder="Enter Roll No."
                />
                {errors.roll_no && (
                  <p className="text-red-500 text-sm">
                    {typeof errors.roll_no.message === "string"
                      ? errors.roll_no.message
                      : "An error occurred"}
                  </p>
                )}
              </div>
              {/* Year of Admission */}
              <div>
                <Label>Year of Admission</Label>
                <Input
                  type="text"
                  {...register("year_of_admission", { required: "Year of Admission is required" })}
                  placeholder="Enter Year of Admission"
                />
                {errors.year_of_admission && (
                  <p className="text-red-500 text-sm">
                    {typeof errors.year_of_admission.message === "string"
                      ? errors.year_of_admission.message
                      : "An error occurred"}
                  </p>
                )}
              </div>
              {/* Password */}
              <div>
                <Label>Password</Label>
                <Input
                  type="password"
                  {...register("password", { required: "Password is required" })}
                  placeholder="Enter Password"
                />
                {errors.password && (
                  <p className="text-red-500 text-sm">
                    {typeof errors.password.message === "string"
                      ? errors.password.message
                      : "An error occurred"}
                  </p>
                )}
              </div>
              {/* Confirm Password */}
              <div>
                <Label>Confirm Password</Label>
                <Input
                  type="password"
                  {...register("confirm_password", { required: "Confirm Password is required" })}
                  placeholder="Confirm Password"
                />
                {errors.confirm_password && (
                  <p className="text-red-500 text-sm">
                    {typeof errors.confirm_password.message === "string"
                      ? errors.confirm_password.message
                      : "An error occurred"}
                  </p>
                )}
              </div>
            </div>
            <div className="flex justify-center gap-4">
              <Button variant="outline" onClick={() => router.push("/student-page")}>
                Cancel
              </Button>
              <Button type="submit" className="bg-[#1E40AF] text-white rounded-[10px] hover:bg-[#1E40AF]">
                Add Student
              </Button>
            </div>
          </form>
        </div>
      </section>
    </>
  );
};

export default AddStudent;
